yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="home"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path

from . import views
from .views import SignUp

app_name = "users"

urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path("signup/", SignUp.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "reset/",
        PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset_form",
    ),
    path(
        "accounts/settings/change_password",
        views.ChangePasswordView.as_view(),
        name="change_password",
    ),
]

yatube/yatube/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from yatube import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"
CSRF_FAILURE_VIEW = "core.views.csrf_failure"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/follow_posts_list.html
{% load thumbnail %}
{% for post in list_posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y"}}
    </li>
  </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
  <p>{{ post.text|truncatechars:255 }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a><br>
  {% if not group and post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи
        группы</a>
  {% endif %}
  {% if not forloop.last %}
    <hr>
  {% endif %}
{% endfor %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:home' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30"
             class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
               href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
               href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая
                запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light"
                 href="{% url 'users:change_password' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

yatube/templates/includes/post_list.html
{% load thumbnail %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
    {% if not author %}
      <a href="{% url 'posts:profile' post.author.username %}">все посты
        пользователя</a>
    {% endif %}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text|truncatechars:255 }}</p>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a><br>
{% if not group and post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи
    группы</a>
{% endif %}
{% if not forloop.last %}
  <hr>
{% endif %}