yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="home"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from yatube import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"
CSRF_FAILURE_VIEW = "core.views.csrf_failure"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Post(CreatedModel):
    MAX_LEN_TEXT = 15

    text = models.TextField(
        verbose_name="Текст поста", help_text="Введите текст поста"
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор записи",
    )
    group = models.ForeignKey(
        "Group",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )

    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return self.text[: self.MAX_LEN_TEXT]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название группы")
    slug = models.SlugField(max_length=50, unique=True, null=False)
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="Запись",
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор записи",
    )

    text = models.TextField(
        "Текст",
        help_text="Текст комментария",
        max_length=300,
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор записи",
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {"text": "Текст поста", "group": "Группа"}
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def get_page_obj(request, post_list):
    return Paginator(post_list, 10).get_page(request.GET.get("page"))


@cache_page(20, key_prefix="index_page")
def index(request):
    post_list = Post.objects.all().select_related("group")
    page_obj = get_page_obj(request, post_list)
    context = {"page_obj": page_obj, "index": True}
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = get_page_obj(request, post_list)
    context = {
        "page_obj": page_obj,
        "group": group,
    }

    return render(request, "posts/group_list.html", context)


def profile(request, username):
    user = get_object_or_404(User.objects.filter(username=username))
    post_list = user.posts.all()
    page_obj = get_page_obj(request, post_list)

    context = {
        "author": user,
        "page_obj": page_obj,
    }

    if request.user.is_authenticated:
        following = request.user.follower.exists()
        context.update(following=following)

    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    page_obj = get_object_or_404(Post.objects.filter(pk=post_id))
    form = CommentForm()
    comments = page_obj.comments.all()
    context = {
        "form": form,
        "page_obj": page_obj,
        "comments": comments,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {"form": form}
    if request.method == "GET" or not form.is_valid():
        return render(request, "posts/create.html", context)
    else:
        form.instance.author = request.user
        form.save()
        return redirect("posts:profile", request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post.objects.filter(pk=post_id))
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    context = {
        "form": form,
        "page_obj": post,
    }
    if post.author.pk != request.user.id:
        return redirect("posts:post_detail", post_id)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)

    context["is_edit"] = True
    return render(request, "posts/create.html", context)


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page_obj(request, posts)
    context = {"page_obj": page_obj, "follow": True}
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    user = get_object_or_404(User, username=username)
    if request.user.username != username:
        Follow.objects.get_or_create(user=request.user, author=user)
    return redirect("posts:profile", username)


@login_required
def profile_unfollow(request, username):
    user = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=user).delete()
    return redirect("posts:profile", username)

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post" action="" enctype="multipart/form-data">
              {% csrf_token %}
              {% load user_filters %}
              {% for field in form %}
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                <ul>
                  <small id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                </ul>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block content %}
  {% include 'posts/includes/follows_swither.html' %}
  <h1>Подписки на авторов</h1>
{% for post in page_obj %}
	{% include 'includes/post_list.html' %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
	<h1>Записи сообщества: {{ group.title }}</h1>
	<p>{{ group.description }}</p>
	{% for post in page_obj %}
		{% include 'includes/post_list.html' %}
	{% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	Последние обновления на сайте
{% endblock %}
{% block content %}
	<h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
	{% include 'includes/post_list.html' %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ page_obj.pub_date|date:"d E Y"}}
      </li>
      {% if page_obj.group %}
        <li class="list-group-item">
          Группа: {{ page_obj.group.title }}
          <a href="{% url 'posts:group_list' page_obj.group.slug %}"><br>
            все записи группы
          </a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ page_obj.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: <span>{{ page_obj.author.posts.count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' page_obj.author.username %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
  {% thumbnail page_obj.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>
      {{ page_obj.text }}
    </p>

  <!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' page_obj.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}
    {% if  user.id and user.id == page_obj.author.pk %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' page_obj.pk %}">
  Редактировать запись
      {% endif %}
    </a>
  </article>
</div>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ post_username.get_full_name }}
{% endblock %}

{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.first_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if following %}
      <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}"
          role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}"
          role="button">
        Подписаться
      </a>
    {% endif %}
  </div>

  {% for post in page_obj %}
    {% include 'includes/post_list.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}